#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on trusty-juno."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-juno',
                                     source='cloud:trusty-updates/juno')
    deployment.run_tests()
