#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on trusty-kilo."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-kilo',
                                     source='cloud:trusty-updates/kilo')
    deployment.run_tests()
