#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on trusty-liberty."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-liberty',
                                     source='cloud:trusty-updates/liberty')
    deployment.run_tests()
