#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on utopic-juno."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='utopic')
    deployment.run_tests()
