#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on wily-liberty."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='wily')
    deployment.run_tests()
