#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on xenial-mitaka."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='xenial')
    deployment.run_tests()
