#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on precise-grizzly."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='precise',
                                     openstack='cloud:precise-grizzly',
                                     source='cloud:precise-updates/grizzly')
    deployment.run_tests()
