#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on trusty-icehouse."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='trusty')
    deployment.run_tests()
