#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on bionic-queens."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='bionic')
    deployment.run_tests()
