#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on xenial-queens."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='xenial',
                                     openstack='cloud:xenial-queens',
                                     source='cloud:xenial-updates/queens')
    deployment.run_tests()
