#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on bionic-rocky."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='bionic',
                                     openstack='cloud:bionic-rocky',
                                     source='cloud:bionic-updates/rocky')
    deployment.run_tests()
