#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on disco-stein."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='disco')
    deployment.run_tests()
