#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on bionic-stein."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='bionic',
                                     openstack='cloud:bionic-stein',
                                     source='cloud:bionic-stein')
    deployment.run_tests()
