#!/usr/bin/python

"""Amulet tests on a basic ceph deployment on xenial-newton."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='xenial',
                                     openstack='cloud:xenial-newton',
                                     source='cloud:xenial-updates/newton')
    deployment.run_tests()
