#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on yakkety-newton."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='yakkety')
    deployment.run_tests()
