#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on artful-pike."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='artful')
    deployment.run_tests()
