#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on xenial-ocata."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='xenial',
                                     openstack='cloud:xenial-ocata',
                                     source='cloud:xenial-updates/ocata')
    deployment.run_tests()
