#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on xenial-pike."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='xenial',
                                     openstack='cloud:xenial-pike',
                                     source='cloud:xenial-updates/pike')
    deployment.run_tests()
