#!/usr/bin/env python

"""Amulet tests on a basic ceph deployment on zesty-ocata."""

from basic_deployment import CephBasicDeployment

if __name__ == '__main__':
    deployment = CephBasicDeployment(series='zesty')
    deployment.run_tests()
