#!/bin/bash

set -e
set -u

# set up ceph package source
# XXX make this a charm config option
cat >/etc/apt/sources.list.d/ceph-brolin.list <<EOF
deb http://archive.admin.canonical.com/ubuntu precise-cat-ceph main
EOF

apt-get update

apt-get -y install ceph

# ceph-prepare-disk uses this, is only "suggests" in the package
apt-get -y install gdisk

exit 0
