#!/usr/bin/env python3
import os
import sys

_path = os.path.dirname(os.path.realpath(__file__))
_hooks = os.path.abspath(os.path.join(_path, '../hooks'))
_root = os.path.abspath(os.path.join(_path, '..'))


def _add_path(path):
    if path not in sys.path:
        sys.path.insert(1, path)

_add_path(_hooks)
_add_path(_root)

import rados
from ceph_ops import connect
from charmhelpers.core.hookenv import action_get, log, action_fail


def remove_pool():
    try:
        pool_name = action_get("name")
        cluster = connect()
        log("Deleting pool: {}".format(pool_name))
        cluster.delete_pool(str(pool_name))  # Convert from unicode
        cluster.shutdown()
    except (rados.IOError,
            rados.ObjectNotFound,
            rados.NoData,
            rados.NoSpace,
            rados.PermissionError) as e:
        log(str(e))
        action_fail(str(e))


if __name__ == '__main__':
    remove_pool()
