#!/usr/bin/env python3
__author__ = 'chris'
import os
import sys

_path = os.path.dirname(os.path.realpath(__file__))
_hooks = os.path.abspath(os.path.join(_path, '../hooks'))
_root = os.path.abspath(os.path.join(_path, '..'))


def _add_path(path):
    if path not in sys.path:
        sys.path.insert(1, path)

_add_path(_hooks)
_add_path(_root)

from charmhelpers.contrib.storage.linux.ceph import get_erasure_profile
from charmhelpers.core.hookenv import action_get, action_set, config


def make_erasure_profile():
    name = action_get("name")
    out = get_erasure_profile(service=config('admin-user'), name=name)
    action_set({'message': out})


if __name__ == '__main__':
    make_erasure_profile()
