#!/usr/bin/env python3
import os
import sys

_path = os.path.dirname(os.path.realpath(__file__))
_hooks = os.path.abspath(os.path.join(_path, '../hooks'))
_root = os.path.abspath(os.path.join(_path, '..'))


def _add_path(path):
    if path not in sys.path:
        sys.path.insert(1, path)

_add_path(_hooks)
_add_path(_root)

from subprocess import CalledProcessError
from charmhelpers.core.hookenv import action_get, config, log, action_fail
from charmhelpers.contrib.storage.linux.ceph import rename_pool

if __name__ == '__main__':
    name = action_get("pool-name")
    new_name = action_get("new-name")
    try:
        rename_pool(service=config('admin-user'), old_name=name, new_name=new_name)
    except CalledProcessError as e:
        log(str(e))
        action_fail("Renaming pool failed with message: {}".format(str(e)))
